# make-gamedata.ps1 -- folds data/*.json into src/core/gamedata.js
#
# Emits a plain (non-module) script that assigns window.ADV.DATA, so the debug
# harness can be opened straight off the filesystem with no dev server. There
# is no Node/Python in this environment, so file:// has to work.

param(
  [string]$DataDir = "$PSScriptRoot\..\data",
  [string]$OutFile = "$PSScriptRoot\..\src\core\gamedata.js"
)

function LoadJson($name) { Get-Content "$DataDir\$name" -Raw | ConvertFrom-Json }

$rooms     = (LoadJson 'rooms.json').rooms
$objects   = (LoadJson 'objects.json').objects
$layoutDoc = LoadJson 'layouts.json'
$behaviour = (LoadJson 'behaviour.json').behaviour

# Trim to what the sim actually needs; drop ROM addresses and b/w palettes.
$slimRooms = $rooms | ForEach-Object {
  [ordered]@{
    id = $_.id; name = $_.name; color = $_.color
    mirrored = $_.mirrored; ballSize = $_.ballSize
    exits = @($_.exits.up, $_.exits.right, $_.exits.down, $_.exits.left)
    walls = $_.walls
  }
}

$slimObjects = $objects | ForEach-Object {
  [ordered]@{
    code = $_.code; name = $_.name; color = $_.color
    width = $(if ($_.nusiz -eq '07') { 32 } else { 8 })
    frames = @($_.frames | ForEach-Object { @{ maxState = $_.maxState; height = $_.height } })
    positionKind = $_.positionKind
    zp = $_.zpPosition
    fixed = $_.fixedPosition
  }
}

$payload = [ordered]@{
  rooms     = $slimRooms
  objects   = $slimObjects
  layouts   = $layoutDoc.layouts
  random    = $layoutDoc.game3Randomised
  behaviour = $behaviour
}

$json = $payload | ConvertTo-Json -Depth 10
$header = @"
// GENERATED by tools/make-gamedata.ps1 from data/*.json -- do not hand-edit.
// Source: Adventure (1978).bin. See ANALYSIS.md for how these tables were read.
window.ADV = window.ADV || {};
window.ADV.DATA =
"@
New-Item -ItemType Directory -Force -Path (Split-Path $OutFile) | Out-Null
Set-Content -Path $OutFile -Value ($header + "`n" + $json + ";`n") -Encoding utf8
Write-Output "wrote $OutFile"
