# make-maps.ps1 -- renders data/rooms.json into a human-readable MAPS.md
param(
  [string]$DataDir = "$PSScriptRoot\..\data",
  [string]$OutFile = "$PSScriptRoot\..\MAPS.md"
)

$doc = Get-Content "$DataDir\rooms.json" -Raw | ConvertFrom-Json
$byId = @{}
foreach ($r in $doc.rooms) { $byId[$r.id] = $r }

$sb = New-Object System.Text.StringBuilder
function W($s) { [void]$sb.AppendLine($s) }

W '# Room maps'
W ''
W 'Generated by `tools/make-maps.ps1` from `data/rooms.json`. Do not hand-edit.'
W ''
W 'Each room is a **40 x 7 cell** grid. One cell is 4 x 16 units in the 160 x 96'
W 'unit play area. `#` is solid wall, `.` is open floor. Rooms marked'
W '*repeated* draw the same left half twice instead of mirroring it -- the only'
W 'two are `14` and `15`, which is what makes that corner of the black maze feel'
W 'subtly wrong.'
W ''
W 'Exit order everywhere in this project is **up, right, down, left**. Exit'
W 'values `>= $80` are game-variant indirections; see `data/behaviour.json`.'
W ''
W '## Adjacency'
W ''
W '| room | name | color | U | R | D | L |'
W '|------|------|-------|---|---|---|---|'
foreach ($r in $doc.rooms) {
  W ('| `{0}` | {1} | `{2}` | `{3}` | `{4}` | `{5}` | `{6}` |' -f $r.id, $r.name, $r.color, $r.exits.up, $r.exits.right, $r.exits.down, $r.exits.left)
}
W ''
W '## Grids'
W ''
foreach ($r in $doc.rooms) {
  $sym = $(if ($r.mirrored) { 'mirrored' } else { '**repeated**' })
  W ('### `{0}` {1}' -f $r.id, $r.name)
  W ''
  W ('color `{0}` (b/w `{1}`) - {2} - ball size {3} - U `{4}` R `{5}` D `{6}` L `{7}`' -f `
      $r.color, $r.colorBW, $sym, $r.ballSize, $r.exits.up, $r.exits.right, $r.exits.down, $r.exits.left)
  W ''
  W '```'
  foreach ($row in $r.walls) { W $row }
  W '```'
  W ''
}
Set-Content -Path $OutFile -Value $sb.ToString() -Encoding utf8
Write-Output "wrote $OutFile"
